### ISSUE TITLE
Push to heroku && run autobuild.py when lesson_format#master is modified

### ISSUE THREAD

**Issue by andylolz** [RaspberryPiFoundation/lesson_format#110]
This repo is super useful for doing this:
https://github.com/ajlai/github-heroku-pusher

**Comment by andylolz** [comment]
This is much simpler than I realised. Instructions here:
https://devcenter.heroku.com/articles/github-integration

**Comment by andylolz** [comment]
@martinpeck is this definitely closable? Doesn’t appear to be… The heroku remote appears to be behind github.

**Comment by martinpeck** [comment]
Are you sure? The logs show it's at SHA: 4cd4399, which is where the tip of tree here is.

**Comment by martinpeck** [comment]
My check built and deployed AFAIK. So did Rik's. I can see that yours failed to build.

**Comment by martinpeck** [comment]
@andylolz I see what you mean (diff between master and heroku/master shows that they're not the same). However, I think this is correct. The github hook results in the code from github.com being built and deployed, NOT the code from the heroku repository. The hook doesn't auto-pull between Heroku git and Github git - it auto deploys from Github.com.

**Comment by andylolz** [comment]
> The logs show it's at SHA: 4cd4399, which is where the tip of tree here is.

You’re right – `heroku logs` does show that. Weird that `git fetch heroku && git log heroku/master` shows the repo is behind – I guess the deployment works some way independent of that repo?

> My check built and deployed AFAIK. So did Rik's. I can see that yours failed to build.

Not sure what you mean? I cancelled a build midway (as I was just watching to check the phantomjs version / to see if the repo appeared up-to-date.)

**Comment by andylolz** [comment]
Sorry – your last message appeared when I pressed comment! Think we reached the same conclusion :) Closing as fixed.

**Comment by andylolz** [comment]
Nope – I don’t think it’s working! I’m not sure what the auto-deploy from github.com involves, but it’s definitely failing to pull in submodules.

Possibly other problems too, but that’s the one showing up in `heroku logs`

**Comment by martinpeck** [comment]
Just found this in the small print on Heroku...

> GitHub repos that use submodules will generally not deploy correctly on Heroku. This is because GitHub does not include submodule contents when repo-content tarballs are generated.

Grrr.

**Comment by martinpeck** [comment]
OK. Here's the plan...
1. turn off github integration for a bit
2. push latest code to heroku git repo
3. package up the pandoc filter, instead of using submodules 
4. remove the git submodule and replace with a package
5. turn on (and test) the github integration
6. ...
7. drink beer

/cc @CodeClubRik @andylolz

**Comment by andylolz** [comment]
cool!
