### ISSUE TITLE
PDF 'test' instructions for HTML / Python

### ISSUE THREAD

**Issue by rikcross** [RaspberryPiFoundation/lesson_format#131]
Currently _all_ PDFs say 'click the green flag to test', which is only applicable to Scratch.

![screen shot 2014-12-22 at 11 47 44](https://cloud.githubusercontent.com/assets/7372432/5524632/69cb9e32-89d0-11e4-9fcd-9dde298f3989.png)

This could be changed to say simply 'run program to test it' (Python) and 'view your page' or similar in HTML.

I also wonder whether the icon for testing generally should be a green flag, when this is something specific to Scratch?

**Comment by CodeClubRik** [comment]
Oh @andylolz I've just remembered why I left out the 'test' checkpoints. They can only be added to the end of an entire activity (as can the challenges) and not at various arbitrary points in the project.

Is there any way around this? If not, it's not the end of the world, as _most_ test points are at the end of activities -- the rest can just be test points without the `{.flag}` marker.

**Comment by andylolz** [comment]
I would bet money that it works that way by design, as a means to gently push a project author towards a consistent style.
