### ISSUE TITLE
Tidy up notices on HTML project view

### ISSUE THREAD

**Issue by andylolz** [RaspberryPiFoundation/lesson_format#138]
There are so many notices that the entire project is below the fold sometimes. This is my screen right now:
![screen shot 2015-02-04 at 09 18 20](https://cloud.githubusercontent.com/assets/464193/6037842/cab7ae06-ac4f-11e4-86f7-93115692d89d.png)

I think this relates to the student / volunteer portals: This is probably fine on the volunteer version; it’s less fine on the student version.

**Comment by martinpeck** [comment]
+1 

Or, perhaps, we should add another notice at the top telling people to scroll down past the notices :)

**Comment by andylolz** [comment]
Ha! ___weeps___

**Comment by CodeClubRik** [comment]
Currently, there's a [project feedback from](https://docs.google.com/a/codeclub.org.uk/forms/d/15QLeJ_aDklioXl5cUyUK1KqZ7lUhCiewl3qiwXOg41M/) that's used for new projects only.

I think that this could be useful for feedback on any project, but I'm not sure where's best to put it. It could be a part of the [documentation](https://github.com/CodeClub/curriculum_documentation/blob/master/README.md), or as a link at the top of each term / language on the projects subdomain?

This may also mean that we could remove the 'Head's up' message from new projects (or at least make it a lot smaller), as there'll just be an opportunity to give feedback more generally.
