### ISSUE TITLE
Bullet points within challenge can be crossed out by clicking the text

### ISSUE THREAD

**Issue by rikcross** [RaspberryPiFoundation/lesson_format#143]
If a challenge has a bullet point list, then clicking the text clicks the checkbox and crosses out the text.
I've probably done a terrible job of explaining that!

![screen shot 2015-02-06 at 18 08 15](https://cloud.githubusercontent.com/assets/7372432/6084774/cb119fdc-ae2b-11e4-819d-65a29374bd70.png)

**Comment by CodeClubRik** [comment]
...this is also true of 'test' boxes.

**Comment by andylolz** [comment]
Absolutely right – this is currently inconsistent.

I’m not sure there’s a super easy fix here. I _think_ it means switching to use checkboxes (instead of pretend checkboxes).

**Comment by martinpeck** [comment]
The behaviour of these checkboxes is more consistent with the way they're supposed to work in general, but is inconsistent with the way the task checkboxes work in the rest of the lesson. 

@CodeClubRik  Which behaviour would you like to see? I suspect it's easier to make the text stop activating the checkboxes, but that's less consistent with the way these controls are, in general, supposed to work in browsers.

**Comment by CodeClubRik** [comment]
Hey @martinpeck I think my only problem is that sometimes children click the text (either to highlight it, or just to keep track of their reading) and they accidentally 'tick off' the task.

Even if the 'checkbox hover' CSS turned the cursor into a pointer, then it'd be more obvious that clicking had an effect on the task.

Whatever we do, I guess it's best to make this consistent with the main activity steps.

**Comment by andylolz** [comment]
> The behaviour of these checkboxes is more consistent with the way they're supposed to work in general

You’re talking about checkbox labels triggering the checkbox they’re `for`? Yeah… I originally made it work that way… Thing is, they’re big blocks of instructions – often including images. Treating them as labels prevents copy/paste, as Rik points out.

+1 for making just the checkbox clickable (and not the label).
