### ISSUE TITLE
PDFs are too long – consider removing padding / auto-resizing images

### ISSUE THREAD

**Issue by rikcross** [RaspberryPiFoundation/lesson_format#148]
We've had more than one volunteer comment that the PDFs for the new projects are quite lengthy (the PDF for 'Lost in Space' is currently 19 pages). This is partly due to the number and size of images. For example, a screenshot image of the Scratch stage takes up about 1/2 an A4 page:

![screen shot 2015-02-24 at 14 42 12](https://cloud.githubusercontent.com/assets/7372432/6351416/5c5ec2b6-bc33-11e4-8851-616a9864c519.png)

I'm not sure what the solution is here? We could:
- Include fewer images (I don't want to do this really, they're helpful!)
- Add something like a `max-width` or `width: 70%;` or something to the PDF CSS.

There's also a lot of wasted space around tall thin images:

![screen shot 2015-02-24 at 14 47 11](https://cloud.githubusercontent.com/assets/7372432/6351518/2314fed4-bc34-11e4-8e97-267c842b2917.png)

Could we text-wrap or anything (I'm aware that's probably really difficult to implement)?

Any ideas greatly appreciated.

cc. @roswilliamscc

**Comment by martinpeck** [comment]
Presumably the layout of the web page, or the PDF when views on screen, is less of a issues - it's the size of the printed material that's a problem, right? It certainly looks like we have a lot of white space, but I wonder if that's a good thing to maintain - increasing the density of the print outs might make them less accessible and harder to follow.

**Comment by andylolz** [comment]
Yeah – I think whitespace is definitely an issue with the PDFs. There’s probably scope for tightening up without making PDFs harder to follow. I’ve reopened #99.

That won’t take a PDF from 19 pages to <10, though. I’m tempted to say (very controversially) that this seems like an editorial issue, rather than a technical one. The big screenshot could be a smaller screenshot; the tall, thin image could perhaps be a short, wide image. \*hides\*

**Comment by CodeClubRik** [comment]
haha i was hoping i wouldn't have to manually resize images :/

**Comment by CodeClubRik** [comment]
Hey @andylolz I just noticed you changed the title of this issue. Does this mean we can auto-resize images for the PDF only (since the length of a webpage doesn't matter) or does it mean that I should manually resize all images?

**Comment by andylolz** [comment]
Nah – I was just rewording because I’m a pedant! Sorry. “Length of PDFs” is more like a topic – you have to click in and read the description to understand what it’s about. Current title is more of a summary of the issue.
