### ISSUE TITLE
lesson_format soon to be retired

### ISSUE THREAD

**Issue by martinpeck** [RaspberryPiFoundation/lesson_format#168]
## What's Happening to lesson_format?

This repository holds software that has, for some time, built the websites that we use to publish our learning materials.

We are currently in the process of building a totally new website to host our learning materials. The static websites that lesson_format builds are limited in what they can do, so we’ve started with something new. As such, the lesson_format project will soon be retired.

The process of retiring lesson_format won’t be a quick one - we won’t be migrating all of our learning materials over to the new website until we’re happy that things are working well. However, this does mean that it’s less likely we’ll be fixing bugs or adding new features here.
## What Next?

The replacement to lesson_format (i.e. the software we’ll be using to build the new website) isn’t yet public on GitHub. We want to take time to make sure the bits we eventually open source make sense as open source projects. We also want to make sure that the replacement is “good enough”. 

Watch this space.

Love and hugs, Code Club

**Comment by musmuris** [comment]
Ah - I just read this after having generated the PDFs for all the projects. The ones currently live on https://www.codeclubprojects.org don't print very well (they are generated as the wrong document size and the font size is too small).
Do you have a timescale on how long it will be before the new system is published?

**Comment by CodeClubRik** [comment]
Hi @musmuris 

We’re aware of the PDF/font issue, and we’re looking at ways to fix this without making the PDFs too long.

Thanks,
Rik.

**Comment by martinpeck** [comment]
I thought it worth adding one small clarification:

It is just this tool, lesson_format, that is being retired. The curriculum repos that it builds are not going away. The scratch, python, web repositories are still used as the source of our project website.

**Comment by Jxr227** [comment]
Not sure how often visited this is but i'll give it my best anyway!
I'm doing a final year dissertation on teaching computer science to children with robotics. For this I've made a ScratchX extension to interface with Turtlebots, however I can't get lesson_format working, lots of command line errors that I can't seem to resolve. Any tips? Any possibility I could get a preview of the new tool? Producing my own curriculum is very important for my dissertation study, and if I can use the code club style that would be absolutely fantastic, because it's familiar!

**Comment by arve0** [comment]
@Jxr227 Take a look at [codeclub_lesson_builder](https://github.com/arve0/codeclub_lesson_builder), it might help you out. Disclaimer, I'm the author.

**Comment by Jxr227** [comment]
@arve0 Taking a look now - Thanks for the tip!

**Comment by Jxr227** [comment]
@arve0 I'm not really sure how this all works. I've got it running, do I need to create index files myself? The main thing I'm after is just the ability to make (standalone) HTML files to support my research as well as PDFs of the same files that can be available as a download.

**Comment by andylolz** [comment]
@Jxr227 if you still need help on this, feel free to email me on a.lulham@gmail.com

**Comment by martinpeck** [comment]
Getting this project working isn't impossible (the README.md is in pretty good shape, but I wouldn't be surprised if it's missing some stuff), but it's not well documented and the code is not exactly easy to get to grips with.

> Producing my own curriculum is very important for my dissertation study, and if I can use the code club style that would be absolutely fantastic, because it's familiar!

It's worth pointing out that the use of the Code Club name and logos etc would not be appropriate on your own projects. 

So, if you're going try and use lesson_format for your own stuff you should not use the Code Club logo or name, and you're going to have to change a bunch of other config/settings (and, maybe, some code) in order to avoid doing so. You also need to avoid reusing the Google Analytics ID, and other site-specific stuff. See `/assets/themes/cc.theme` for an example of how you can do some of this.

All of this might actually mean it'd be easier for you to create your own static site using something like Jekyll, and then either manually create the PDFs or use Phantom JS to do so. Jekyll is way better documented, and still allows you to work in Markdown.

lesson_format has never been a very good project when it comes to repurposing it to build your own stuff. It's designed for one job only; building a specific website for Code Club.

I'm going to lock this conversation (as it was originally intended as an announcement) but if you have any further questions then please e-mail projects@codeclub.org.uk.
