### ISSUE TITLE
Notes/Extras cannot have embedded files

### ISSUE THREAD

**Issue by andylolz** [RaspberryPiFoundation/lesson_format#55]
Issue raised in the “Bugs/Features Missing” section of the README.

Only projects can have embedded files. Notes/extras can’t.

**Comment by CodeClubRik** [comment]
It would be great to have embedded files, as I'm currently in the process of writing more 'extras' the the new web curriculum.

**Comment by CodeClubRik** [comment]
FYI I've fixed this in a really hacky way, by using relative links to files in the first projects' folder:

https://github.com/CodeClub/webdev-curriculum/commit/194f7086f8891da7f29d385594aafd4e68bfe95c

This may need undoing once this issue is addressed.
