### ISSUE TITLE
URLs and broken links

### ISSUE THREAD

**Issue by rikcross** [RaspberryPiFoundation/lesson_format#83]
I don't know whether this is easily doable, but if a link, such as:
http://projects.codeclub.org.uk/en-GB/01_scratch_01/01/01%20Felix%20and%20Herbert.html

...could become something like...
http://projects.codeclub.org.uk/en-GB/scratch_01/Felix%20and%20Herbert.html

...then there wouldn't be broken links whenever I move the order of terms/projects around. For example, adding in a project as lesson 1 shifts the number of all subsequent lessons by 1, and breaks links.

**Comment by andylolz** [comment]
I ★★★’d this ages ago and self-assigned, then didn’t do it! So… This is next up. I’ll also create redirects for this, since otherwise it will break pretty much all existing URLs.

**Comment by andylolz** [comment]
Unassigning because it’s ★★★ and not a big task… But I’m v unlikely to do it.
