### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by andylolz** [RaspberryPiFoundation/lesson_format#98]
There’s no license on this repo. [May I suggest MIT](http://choosealicense.com/licenses/mit/)?

**Comment by andylolz** [comment]
Ping! Any word on this? I’m now far more keen on [GPL](choosealicense.com/licenses/gpl-2.0/).

**Comment by CodeClubRik** [comment]
@martinpeck probably has some thoughts on this.

**Comment by andylolz** [comment]
Any word on this?

**Comment by martinpeck** [comment]
For no good reason I've generally gone with MIT, rather than GPL. I've worked at companies in the past that have been fearful (sometimes incorrectly) of GPL, where as they are generally pretty cool with MIT. Let me add this to my TODO to discuss with our legal dudes.

**Comment by andylolz** [comment]
Cool – thanks. There’s a tiny bit more info on #114.
